online_library_system/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('online_library_system_app.urls')),
]

online_library_system_app/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('',views.index, name='index'),
    path('add-author/', views.add_author, name='add_author'),
    path('add-book/', views.add_book, name='add_book'),
    path('add-borrow-record/', views.add_borrow_record, name='add_borrow_record'),
    path('authors/', views.author_list, name='author_list'),
    path('books/', views.book_list, name='book_list'),
    path('borrow-records/', views.borrow_list, name='borrow_list'),
    path('export-excel-author/', views.export_to_excel_author, name='export_to_excel_author'),
    path('export-excel-book/', views.export_to_excel_book, name='export_to_excel_book'),
    path('export-excel-borrow-record/', views.export_to_excel_borrow_record, name='export_to_excel_borrow_record'),
    path('export-excel-author-book-borrow-record/', views.export_to_excel_author_book_borrow_record, name='export_to_excel_author_book_borrow_record'),
]

online_library_system_app/models.py
from django.db import models
from django.core.exceptions import ValidationError
from django.utils.dateparse import parse_date
import re

class Author(models.Model):
    name = models.CharField(max_length=100)
    email = models.EmailField(max_length=100, unique=True)
    bio = models.TextField()

    def clean(self):
        if not re.match(r'^[A-Za-z\s]+$', self.name):
            raise ValidationError('Name can only contain letters and spaces.')
        if not re.match(r'^[a-zA-Z0-9_.+-]+@[a-zA-Z0-9-]+\.[a-zA-Z0-9-.]+$', self.email):
            raise ValidationError('Enter a valid email address.')

    def __str__(self):
        return self.name

class Book(models.Model):
    title = models.CharField(max_length=200)
    genre = models.CharField(max_length=100)
    published_date = models.DateField()
    author = models.ForeignKey(Author, on_delete=models.CASCADE)

    def clean(self):
        if not self.title:
            raise ValidationError('Title is required.')
        if not self.genre:
            raise ValidationError('Genre is required.')
        if not parse_date(str(self.published_date)):
            raise ValidationError('Enter a valid date in YYYY-MM-DD format.')

    def __str__(self):
        return self.title

class BorrowRecord(models.Model):
    user_name = models.CharField(max_length=100)
    book = models.ForeignKey(Book, on_delete=models.CASCADE)
    borrow_date = models.DateField()
    return_date = models.DateField()

    def clean(self):
        if not re.match(r'^[A-Za-z\s]+$', self.user_name):
            raise ValidationError('User name can only contain letters and spaces.')
        if not parse_date(str(self.borrow_date)):
            raise ValidationError('Enter a valid borrow date in YYYY-MM-DD format.')
        if not parse_date(str(self.return_date)):
            raise ValidationError('Enter a valid return date in YYYY-MM-DD format.')

    def __str__(self):
        return self.user_name

online_library_system_app/forms.py
from django import forms
from .models import Author, Book, BorrowRecord
from django.core.exceptions import ValidationError
from django.utils.dateparse import parse_date
import re

class AuthorForm(forms.ModelForm):
    class Meta:
        model = Author
        fields = ['name', 'email', 'bio']

    def clean_name(self):
        name = self.cleaned_data.get('name')
        if not name:
            raise ValidationError('Name is required.')
        if not re.match(r'^[A-Za-z\s]+$', name):
            raise ValidationError('Name can only contain letters and spaces.')
        return name

    def clean_email(self):
        email = self.cleaned_data.get('email')
        if not email:
            raise ValidationError('Email is required.')
        if not re.match(r'^[a-zA-Z0-9_.+-]+@[a-zA-Z0-9-]+\.[a-zA-Z0-9-.]+$', email):
            raise ValidationError('Enter a valid email address.')
        if Author.objects.filter(email=email).exists():
            raise ValidationError('An author with this email already exists, Please different email id fill this form.')
        return email

    def clean_bio(self):
        bio = self.cleaned_data.get('bio')
        if not bio:
            raise ValidationError('Bio is required.')
        return bio

class BookForm(forms.ModelForm):
    class Meta:
        model = Book
        fields = ['title', 'genre', 'published_date', 'author']

    def clean_title(self):
        title = self.cleaned_data.get('title')
        if not title:
            raise ValidationError('Title is required.')
        return title

    def clean_genre(self):
        genre = self.cleaned_data.get('genre')
        if not genre:
            raise ValidationError('Genre is required.')
        return genre
    
    def clean_published_date(self):
        published_date = self.cleaned_data.get('published_date')
        if not published_date:
            raise ValidationError('Published date is required.')
        try:
            # Convert published_date to string and then parse it
            published_date_str = str(published_date)
            if not parse_date(published_date_str):
                raise ValidationError('Enter a valid date in YYYY-MM-DD format.')
        except ValueError:
            raise ValidationError('Enter a valid date in YYYY-MM-DD format.')
        return published_date

class BorrowRecordForm(forms.ModelForm):
    class Meta:
        model = BorrowRecord
        fields = ['user_name', 'book', 'borrow_date', 'return_date']

    def clean_user_name(self):
        user_name = self.cleaned_data.get('user_name')
        if not user_name:
            raise ValidationError('User name is required.')
        if not re.match(r'^[A-Za-z\s]+$', user_name):
            raise ValidationError('User name can only contain letters and spaces.')
        return user_name

    def clean_borrow_date(self):
        borrow_date = self.cleaned_data.get('borrow_date')
        if not borrow_date:
            raise ValidationError('Borrow date is required.')
        try:
            # Convert borrow_date to string and then parse it
            borrow_date_str = str(borrow_date)
            if not parse_date(borrow_date_str):
                raise ValidationError('Enter a valid date in YYYY-MM-DD format.')
        except ValueError:
            raise ValidationError('Enter a valid date in YYYY-MM-DD format.')
        return borrow_date

    def clean_return_date(self):
        return_date = self.cleaned_data.get('return_date')
        if not return_date:
            raise ValidationError('Return date is required.')
        try:
            # Convert return_date to string and then parse it
            return_date_str = str(return_date)
            if not parse_date(return_date_str):
                raise ValidationError('Enter a valid date in YYYY-MM-DD format.')
        except ValueError:
            raise ValidationError('Enter a valid date in YYYY-MM-DD format.')
        return return_date

online_library_system_app/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.http import HttpResponse
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from .models import Author, Book, BorrowRecord
from django.utils.dateparse import parse_date
import openpyxl
from .forms import AuthorForm, BookForm, BorrowRecordForm
from django.contrib import messages
from django.core.exceptions import ValidationError
import re

def index(request):
    return render(request, 'index.html')

def validate_author_data(name, email, bio):
    errors = {}
    if not re.match(r'^[A-Za-z\s]+$', name):
        errors['name'] = 'Name can only contain letters and spaces.'
        raise ValidationError('Name can only contain letters and spaces.')
    if not re.match(r'^[a-zA-Z0-9_.+-]+@[a-zA-Z0-9-]+\.[a-zA-Z0-9-.]+$', email):
        errors['email'] = 'Enter a valid email address.'
        raise ValidationError('Enter a valid email address.')
    if not bio:
        errors['bio'] = 'Bio cannot be empty.'
        raise ValidationError('Bio cannot be empty.')
    return errors

def add_author(request):
    if request.method == 'POST':
        form = AuthorForm(request.POST)
        if form.is_valid():
            name = form.cleaned_data.get('name')
            email = form.cleaned_data.get('email')
            bio = form.cleaned_data.get('bio')

            try:
                errors = validate_author_data(name, email, bio)
                if not errors:
                    form.save()
                    messages.success(request, 'Author added successfully!')
                    return redirect('author_list')
                else:
                    for field, error in errors.items():
                        form.add_error(field, error)
                    messages.error(request, 'Error adding author. Please correct the errors below.')
            except ValidationError as e:
                form.add_error(None, e.message)
        else:
            messages.error(request, 'Error adding author, Please all fields are required. Please correct the errors below.')
    else:
        form = AuthorForm()
    return render(request, 'add_author.html', {'form': form})

def validate_book_data(title, genre, published_date):
    errors = {}
    if not title:
        errors['title'] = 'Title is required.'
        raise ValidationError('Title is required.')
    if not genre:
        errors['genre'] = 'Genre is required.'
        raise ValidationError('Genre is required.')
    try:
        parse_date(str(published_date))
    except ValueError:
        errors['published_date'] = 'Enter a valid date in YYYY-MM-DD format.'
        raise ValidationError('Enter a valid date in YYYY-MM-DD format.')
    return errors

def add_book(request):
    if request.method == 'POST':
        form = BookForm(request.POST)
        if form.is_valid():
            title = form.cleaned_data.get('title')
            genre = form.cleaned_data.get('genre')
            published_date = form.cleaned_data.get('published_date')

            try:
                errors = validate_book_data(title, genre, published_date)
                if not errors:
                    form.save()
                    messages.success(request, 'Book added successfully!')
                    return redirect('book_list')
                else:
                    for field, error in errors.items():
                        form.add_error(field, error)
                    messages.error(request, 'Error adding book. Please correct the errors below.')
            except ValidationError as e:
                form.add_error(None, e.message)
        else:
            messages.error(request, 'Error adding book, Please all fields are required. Please correct the errors below.')
    else:
        form = BookForm()
    authors = Author.objects.all()
    return render(request, 'add_book.html', {'form': form, 'authors': authors})

def validate_borrow_record_data(user_name, borrow_date, return_date):
    errors = {}
    if not re.match(r'^[A-Za-z\s]+$', user_name):
        errors['user_name'] = 'User name can only contain letters and spaces.'
        raise ValidationError('User name can only contain letters and spaces.')
    try:
        parse_date(str(borrow_date))
    except ValueError:
        errors['borrow_date'] = 'Enter a valid borrow date in YYYY-MM-DD format.'
        raise ValidationError('Enter a valid borrow date in YYYY-MM-DD format.')
    try:
        parse_date(str(return_date))
    except ValueError:
        errors['return_date'] = 'Enter a valid return date in YYYY-MM-DD format.'
        raise ValidationError('Enter a valid return date in YYYY-MM-DD format.')
    return errors

def add_borrow_record(request):
    if request.method == 'POST':
        form = BorrowRecordForm(request.POST)
        if form.is_valid():
            user_name = form.cleaned_data.get('user_name')
            borrow_date = form.cleaned_data.get('borrow_date')
            return_date = form.cleaned_data.get('return_date')

            try:
                errors = validate_borrow_record_data(user_name, borrow_date, return_date)
                if not errors:
                    form.save()
                    messages.success(request, 'Borrow record added successfully!')
                    return redirect('borrow_list')
                else:
                    for field, error in errors.items():
                        form.add_error(field, error)
                    messages.error(request, 'Error adding borrow record. Please correct the errors below.')
            except ValidationError as e:
                form.add_error(None, e.message)
        else:
            messages.error(request, 'Error adding borrow record, Please all fields are required. Please correct the errors below.')
    else:
        form = BorrowRecordForm()
    books = Book.objects.all()
    return render(request, 'add_borrow_record.html', {'form': form, 'books': books})

def author_list(request):
    authors = Author.objects.all().order_by('id')
    paginator = Paginator(authors, 5)
    page = request.GET.get('page')

    try:
        authors = paginator.page(page)
    except PageNotAnInteger:
        authors = paginator.page(1)
    except EmptyPage:
        authors = paginator.page(paginator.num_pages)

    context = {'authors': authors}
    return render(request, 'author_list.html', context)

def book_list(request):
    books = Book.objects.all().order_by('id')
    paginator = Paginator(books, 5)
    page = request.GET.get('page')

    try:
        books = paginator.page(page)
    except PageNotAnInteger:
        books = paginator.page(1)
    except EmptyPage:
        books = paginator.page(paginator.num_pages)

    context = {'books': books}
    return render(request, 'book_list.html', context)

def borrow_list(request):
    records = BorrowRecord.objects.all().order_by('id')
    paginator = Paginator(records, 5)
    page = request.GET.get('page')

    try:
        records = paginator.page(page)
    except PageNotAnInteger:
        records = paginator.page(1)
    except EmptyPage:
        records = paginator.page(paginator.num_pages)

    context = {'records': records}
    return render(request, 'borrow_list.html', context)

def export_to_excel_author(request):
    response = HttpResponse(content_type='application/ms-excel')
    response['Content-Disposition'] = 'attachment; filename=library_data.xlsx'

    wb = openpyxl.Workbook()
    author_ws = wb.active
    author_ws.title = 'Authors'

    # Export Authors
    authors = Author.objects.all()
    author_ws.append(['ID', 'Name', 'Email', 'Bio'])
    for author in authors:
        author_ws.append([author.id, author.name, author.email, author.bio])

    wb.save(response)
    return response
    
def export_to_excel_book(request):
    response = HttpResponse(content_type='application/ms-excel')
    response['Content-Disposition'] = 'attachment; filename=library_data.xlsx'

    wb = openpyxl.Workbook()
    books_ws = wb.active
    books_ws.title = 'Books'

    # Export Books
    books = Book.objects.all()
    books_ws.append(['ID', 'Title', 'Genre', 'Published Date', 'Author'])
    for book in books:
        books_ws.append([book.id, book.title, book.genre, book.published_date, book.author.name])

    wb.save(response)
    return response

def export_to_excel_borrow_record(request):
    response = HttpResponse(content_type='application/ms-excel')
    response['Content-Disposition'] = 'attachment; filename=library_data.xlsx'

    wb = openpyxl.Workbook()
    borrow_records_ws = wb.active
    borrow_records_ws.title = 'Borrow Records'

    # Export Borrow Records
    borrow_records = BorrowRecord.objects.all()
    borrow_records_ws.append(['ID', 'User Name', 'Book', 'Borrow Date', 'Return Date'])
    for record in borrow_records:
        borrow_records_ws.append([record.id, record.user_name, record.book.title, record.borrow_date, record.return_date])

    wb.save(response)
    return response

def export_to_excel_author_book_borrow_record(request):
    response = HttpResponse(content_type='application/ms-excel')
    response['Content-Disposition'] = 'attachment; filename=library_data.xlsx'

    wb = openpyxl.Workbook()
    author_ws = wb.active
    author_ws.title = 'Authors'

    # Export Authors
    authors = Author.objects.all()
    author_ws.append(['ID', 'Name', 'Email', 'Bio'])
    for author in authors:
        author_ws.append([author.id, author.name, author.email, author.bio])

    books_ws = wb.active
    books_ws.title = 'Books'

    # Export Books
    books = Book.objects.all()
    books_ws.append(['ID', 'Title', 'Genre', 'Published Date', 'Author'])
    for book in books:
        books_ws.append([book.id, book.title, book.genre, book.published_date, book.author.name])

    borrow_records_ws = wb.active
    borrow_records_ws.title = 'Borrow Records'

    # Export Borrow Records
    borrow_records = BorrowRecord.objects.all()

online_library_system_app/templates/add_author.html
{% extends 'base.html' %}

{% block title %}Add Book{% endblock %}

{% block content %}

<head>
    <style>
        .error {
            color: red;
        }
    </style>
</head>

<h2>Add Author</h2>

<form method="post">
    {% csrf_token %}
    <div>
        <label for="id_name">Name:</label>
        {{ form.name }}
        {% if form.name.errors %}
        <div style="color: red;" id="id_name">
            {{ form.name.errors }}
        </div>
        <span id="name-help"></span>
        {% endif %}
    </div>
    <div>
        <label for="id_email">Email:</label>
        {{ form.email }}
        {% if form.email.errors %}
        <div style="color: red;">
            {{ form.email.errors }}
        </div>
        {% endif %}
    </div>
    <div>
        <label for="id_bio">Bio:</label>
        {{ form.bio }}
        {% if form.bio.errors %}
        <div style="color: red;">
            {{ form.bio.errors }}
        </div>
        {% endif %}
    </div>
    <button class="btn btn-primary" type="submit">Add Author</button>
</form>

{% endblock %}

online_library_system_app/templates/add_book.html
{% extends 'base.html' %}

{% block title %}Add Book{% endblock %}

{% block content %}
    <h2>Add Book</h2>

    <form method="post">
        {% csrf_token %}
        <div>
            <label for="id_title">Title:</label>
            {{ form.title }}
            {% if form.title.errors %}
                <div style="color: red;">
                    {{ form.title.errors }}
                </div>
            {% endif %}
        </div>
        <div>
            <label for="id_genre">Genre:</label>
            {{ form.genre }}
            {% if form.genre.errors %}
                <div style="color: red;">
                    {{ form.genre.errors }}
                </div>
            {% endif %}
        </div>
        <div>
            <label for="id_published_date">Published Date:</label>
            <input type="date" id="published_date" name="published_date">
            {% if form.published_date.errors %}
                <div style="color: red;">
                    {{ form.published_date.errors }}
                </div>
            {% endif %}
        </div>
        <div>
            <label for="id_author">Author:</label>
            {{ form.author }}
            {% if form.author.errors %}
                <div style="color: red;">
                    {{ form.author.errors }}
                </div>
            {% endif %}
        </div>
        <button class="btn btn-primary" type="submit">Add Book</button>
    </form>

{% endblock %}

online_library_system_app/templates/add_borrow_record.html
{% extends 'base.html' %}

{% block title %}Add Borrow Record{% endblock %}

{% block content %}
    <h2>Add Borrow Record</h2>

    <form method="post">
        {% csrf_token %}
        <div>
            <label for="id_user_name">User Name:</label>
            {{ form.user_name }}
            {% if form.user_name.errors %}
                <div style="color: red;">
                    {{ form.user_name.errors }}
                </div>
            {% endif %}
        </div>
        <div>
            <label for="id_book">Book:</label>
            {{ form.book }}
            {% if form.book.errors %}
                <div style="color: red;">
                    {{ form.book.errors }}
                </div>
            {% endif %}
        </div>
        <div>
            <label for="id_borrow_date">Borrow Date:</label>
            <input type="date" id="borrow_date" name="borrow_date">
            {% if form.borrow_date.errors %}
                <div style="color: red;">
                    {{ form.borrow_date.errors }}
                </div>
            {% endif %}
        </div>
        <div>
            <label for="id_return_date">Return Date:</label>
            <input type="date" id="return_date" name="return_date">
            {% if form.return_date.errors %}
                <div style="color: red;">
                    {{ form.return_date.errors }}
                </div>
            {% endif %}
        </div>
        <button class="btn btn-primary" type="submit">Add Borrow Record</button>
    </form>

{% endblock %}

online_library_system_app/templates/author_list.html
{% extends 'base.html' %}

{% block title %}Book List{% endblock %}

{% block content %}

<div class="container">
    <div class="jumbotron">
        <h1>View All Authors Details Lists</h1>
        <table class="table table-dark table-striped">
            <thead>
                <tr>
                    <th scope="col">Id</th>
                    <th scope="col">Name</th>
                    <th scope="col">Email</th>
                    <th scope="col">Bio</th>
                </tr>
            </thead>
            <tbody>
                {% for author in authors %}
                <tr>
                    <th scope="row">{{ author.id }}</th>
                    <td>{{ author.name }}</td>
                    <td>{{ author.email }}</td>
                    <td>{{ author.bio }}</td>
                </tr>
                {% endfor %}
            </tbody>
        </table>
        <nav aria-label="Page navigation">
            <ul class="pagination">
                {% if authors.has_previous %}
                <li class="page-item">
                    <a class="page-link" href="?page=1" tabindex="-1">First</a>
                </li>
                <li class="page-item">
                    <a class="page-link" href="?page={{ authors.previous_page_number }}" tabindex="-1">Previous</a>
                </li>
                {% endif %}
                {% for num in authors.paginator.page_range %}
                {% if authors.number == num %}
                <li class="page-item active"><a class="page-link" href="#">{{ num }} <span
                            class="sr-only">(current)</span></a></li>
                {% else %}
                <li class="page-item"><a class="page-link" href="?page={{ num }}">{{ num }}</a></li>
                {% endif %}
                {% endfor %}
                {% if authors.has_next %}
                <li class="page-item">
                    <a class="page-link" href="?page={{ authors.next_page_number }}">Next</a>
                </li>
                <li class="page-item">
                    <a class="page-link" href="?page={{ authors.paginator.num_pages }}">Last</a>
                </li>
                {% endif %}
            </ul>
        </nav>
    </div>
</div>

{% endblock %}

online_library_system_app/templates/base.html
<!DOCTYPE html>
<html>

<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap.min.css">
    <title>{% block title %}{% endblock %}</title>
    {% load static %}
    <link rel="stylesheet" href="{% static 'css/styles.css' %}">
    <style>
        .messages {
            list-style-type: none;
            padding: 0;
        }

        .messages li {
            margin-bottom: 10px;
            padding: 10px;
            border-radius: 5px;
        }

        .messages li.success {
            background-color: #d4edda;
            color: #155724;
        }

        .messages li.error {
            background-color: #f8d7da;
            color: #721c24;
        }

        .messages li.info {
            background-color: #d1ecf1;
            color: #0c5460;
        }

        .messages li.warning {
            background-color: #fff3cd;
            color: #856404;
        }
    </style>
</head>

<body>
    <!-- Navigation Bar -->
    <hearder>
        <nav class="navbar navbar-inverse">
            <div class="container-fluid">
                <div class="navbar-header">
                    <a class="navbar-brand" href="#">Online Library Management System</a>
                </div>
                <ul class="nav navbar-nav">
                    <li class="active"><a href="/">Home</a></li>
                    <li><a href="/add-author">Add Author</a></li>
                    <li><a href="/add-book">Add Book</a></li>
                    <li><a href="/add-borrow-record">Add Borrow Record</a></li>
                    <li>
                        <div class="dropdown">
                            <button class="dropbtn">View List</button>
                            <div class="dropdown-content">
                                <a href="/authors">Authors List</a>
                                <a href="/books">Book List</a>
                                <a href="/borrow-records">Borrow Record List</a>
                            </div>
                        </div>
                    </li>
                    <li>
                        <div class="dropdown">
                            <button class="dropbtn">Excel Sheet List</button>
                            <div class="dropdown-content">
                                <a href="/export-excel-author">Export Excel Sheet Authors</a>
                                <a href="/export-excel-book">Export Excel Sheet Book</a>
                                <a href="/export-excel-borrow-record">Export Excel Sheet Borrow Record</a>
                                <a href="/export-excel-author-book-borrow-record">Export Excel Sheet Author, Book,
    Borrow Record</a>
                            </div>
                        </div>
                    </li>
                </ul>
            </div>
        </nav>
    </hearder>
    {% if messages %}
    <ul class="messages">
        {% for message in messages %}
        <li{% if message.tags %} class="{{ message.tags }}" {% endif %}>{{ message }}</li>
            {% endfor %}
    </ul>
    {% endif %}
    {% block content %}
    {% endblock %}
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.7.1/jquery.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/js/bootstrap.min.js"></script>
</body>

</html>

online_library_system_app/templates/book_list.html
{% extends 'base.html' %}

{% block title %}Book List{% endblock %}

{% block content %}

<div class="container">
    <div class="jumbotron">
        <h1>View All Book Details Lists</h1>

        <table class="table table-dark table-striped">
            <thead>
                <tr>
                    <th scope="col">Book Id</th>
                    <th scope="col">Title</th>
                    <th scope="col">Genre</th>
                    <th scope="col">Published Date</th>
                    <th scope="col">Author</th>
                </tr>
            </thead>
            <tbody>
                {% for book in books %}
                <tr>
                    <th scope="row">{{ book.id }}</th>
                    <td>{{ book.title }}</td>
                    <td>{{ book.genre }}</td>
                    <td>{{ book.published_date }}</td>
                    <td>{{ book.author.name }}</td>
                </tr>
                {% endfor %}
            </tbody>
        </table>
        <nav aria-label="Page navigation">
            <ul class="pagination">
                {% if books.has_previous %}
                <li class="page-item">
                    <a class="page-link" href="?page=1" tabindex="-1">First</a>
                </li>
                <li class="page-item">
                    <a class="page-link" href="?page={{ books.previous_page_number }}" tabindex="-1">Previous</a>
                </li>
                {% endif %}
                {% for num in books.paginator.page_range %}
                {% if books.number == num %}
                <li class="page-item active"><a class="page-link" href="#">{{ num }} <span
                            class="sr-only">(current)</span></a></li>
                {% else %}
                <li class="page-item"><a class="page-link" href="?page={{ num }}">{{ num }}</a></li>
                {% endif %}
                {% endfor %}
                {% if books.has_next %}
                <li class="page-item">
                    <a class="page-link" href="?page={{ books.next_page_number }}">Next</a>
                </li>
                <li class="page-item">
                    <a class="page-link" href="?page={{ books.paginator.num_pages }}">Last</a>
                </li>
                {% endif %}
            </ul>
        </nav>
    </div>
</div>
{% endblock %}

online_library_system_app/templates/index.html
{% extends 'base.html' %}

{% block title %}Add Book{% endblock %}

{% block content %}
        <h1>Library Management System, Hello, this is the library app!</h1>
{% endblock %}